feat: add to datadog

diff --git a/.github/workflows/postman-tests.yml b/.github/workflows/postman-tests.yml
--- a/.github/workflows/postman-tests.yml
+++ b/.github/workflows/postman-tests.yml
@@ -90,10 +90,13 @@ jobs:
         if: ${{ steps.check-tests.outputs.skip == 'false' }}
         run: |
           echo "${{ steps.get-run.outputs.run_id }}" > .last_upstream_run_id.txt
+          # Clean up the temporary file so it doesn't cause git to complain
+          rm -f last_run_id.txt
           git config user.name "github-actions"
           git config user.email "github-actions@github.com"
           git add .last_upstream_run_id.txt
-          git commit -m "[skip ci] Update last processed upstream run id to ${{ steps.get-run.outputs.run_id }}"
+          # Commit if there are changes; if not, continue without error.
+          git commit -m "[skip ci] Update last processed upstream run id to ${{ steps.get-run.outputs.run_id }}" || echo "No changes to commit."
           git push
 
       # 6. Install Newman, NordLayer, and Datadog CI CLI dependencies.
